### ISSUE TITLE
Feature: Page Selector

### ISSUE THREAD

**Issue by FrosteByte** [BluSpring/EnhancedBookWriting#2]
I love minimal mods like this! What I wish for even more than page deletion/addition is to be able to jump to the end of a book to keep writing, or to jump to a specific page (table of contents). I would be very interested to see that added to this mod.

Thanks!

**Comment by BluSpring** [comment]
I'm unsure if I can do a table of contents system, but I can probably do a "jump to specific page", though it's probably going to be slightly less inconvenient rather than just flipping through each page individually.

As for the "jump to start/end", I can absolutely do that, I'll do that it in a bit

**Comment by BluSpring** [comment]
Added in 571121113a270f4ec325c10d08f2dc3d9c200916, for update v1.1.0 :)
